Feature/move scripts to avatar loader
readyplayerme/Unity-Core pull request #26
Opened 2022-12-08 13:30 UTC by rYuuk

## [TICKETID](https://ready-player-me.monday.com/boards/2563815861/pulses/TICKETID)

## Description

-   Briefly describe what this change will do

## Changes

#### Added

-   List your additions and new features here.

#### Updated

-   List your updates and changes here.

#### Removed

-   List what is removed here.

## How to Test

-   Add steps to locally test these changes

## Checklist

-   [ ] Tests written or updated for the changes.
-   [ ] Documentation is updated.
-   [ ] Changelog is updated.
-   [ ] QA Testing is updated.

## QA Testing

-   Mention any useful test cases for this feature and add to QA Testing documentation.

## Details

-   If more details are necessary to support the description with images and videos add them here.

2022-12-12 10:53 UTC, HarrisonHough requested changes
Looks good, one small thing in the comments (just need to update SubDomain to Subdomain)

2022-12-12 10:53 UTC, HarrisonHough commented on Editor/EditorAssetLoader.cs
> +            CreatePartnerSubDomainSetting();
SubDomain should be Subdomain. 

Kind of a side note but we could perhaps use PartnerName. or a PartnerSettings object with property Name. However not sure if there would ever be any other "Partner Settings" in future :D 

anyways PartnerSubdomainSettings is fine

2022-12-12 13:09 UTC, srcnalt commented
I get error messages for `using ReadyPlayerMe.AvatarLoader;` in Core. Core loads AvatarLoader, and until it is loaded does not have any knowledge of its code base. So we should not mention any code of other modules.

You can import Core into an empty Unity project and see if they show up. 
<img width="658" alt="image" src="https://user-images.githubusercontent.com/3163281/207053146-6535d1f5-df26-4b1f-b0c2-6e302b1c6320.png">

2022-12-13 07:58 UTC, HarrisonHough commented
> I get error messages for `using ReadyPlayerMe.AvatarLoader;` in Core. Core loads AvatarLoader, and until it is loaded does not have any knowledge of its code base. So we should not mention any code of other modules.
> 
> You can import Core into an empty Unity project and see if they show up. <img alt="image" width="658" src="https://user-images.githubusercontent.com/3163281/207053146-6535d1f5-df26-4b1f-b0c2-6e302b1c6320.png">

yep this include can be removed, probably just something you missed 

![image](https://user-images.githubusercontent.com/7085672/207258877-c7d77437-19e1-4ce8-9886-e2e6d54f2d4d.png)

2022-12-13 12:31 UTC, HarrisonHough approved these changes
Looks good now

2022-12-13 12:37 UTC, merged